repos:
- repo: https://github.com/pycqa/isort
  rev: 5.5.1
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
    - id: flake8
      additional_dependencies: 
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-pytest
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
    - id: mypy
      exclude: ^docs/conf.py
- repo: https://github.com/terrencepreilly/darglint
  rev: v1.5.3
  hooks:
    - id: darglint
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.3.0
  hooks:
    - id: commitizen
      stages: [commit-msg]
